USE COMERCIO;

SELECT 
      C.NOME, 
      IFNULL(C.EMAIL, 'NAO POSSUI EMAIL'), 
      E.ESTADO, 
      T.NUMERO
FROM CLIENTE AS C
INNER JOIN ENDERECO AS E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE AS T
ON C.IDCLIENTE = T.ID_CLIENTE;


SELECT 
      C.NOME, 
      IFNULL(C.EMAIL, 'NAO POSSUI EMAIL') AS EMAIL, 
      E.ESTADO, 
      T.NUMERO
FROM CLIENTE AS C
INNER JOIN ENDERECO AS E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE AS T
ON C.IDCLIENTE = T.ID_CLIENTE;

SELECT C.NOME, 
       C.SEXO, 
       C.EMAIL, 
       T.TIPO, 
       T.NUMERO, 
       E.BAIRRO, 
       E.CIDADE, 
       E.ESTADO
FROM CLIENTE AS C
INNER JOIN ENDERECO AS E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE AS T
ON C.IDCLIENTE = T.ID_CLIENTE


/* VIEWS */

CREATE VIEW RELATORIO AS
SELECT C.NOME, 
       C.SEXO, 
       C.EMAIL, 
       T.TIPO, 
       T.NUMERO, 
       E.BAIRRO, 
       E.CIDADE, 
       E.ESTADO
FROM CLIENTE AS C
INNER JOIN ENDERECO AS E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE AS T
ON C.IDCLIENTE = T.ID_CLIENTE

SELECT * FROM RELATORIO;

/* Localizando views dentro do banco: SHOW TABLES */

DROP VIEW RELATORIO;

CREATE VIEW V_RELATORIO AS
SELECT C.NOME, 
       C.SEXO, 
       C.EMAIL, 
       T.TIPO, 
       T.NUMERO, 
       E.BAIRRO, 
       E.CIDADE, 
       E.ESTADO
FROM CLIENTE AS C
INNER JOIN ENDERECO AS E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE AS T
ON C.IDCLIENTE = T.ID_CLIENTE;


/*Fazendo um select da view*/

SELECT NOME, NUMERO, ESTADO
FROM V_RELATORIO;



/*UPDATE, INSERT E DELETE - DML */
INSERT INTO V_RELATORIO VALUES (
      'ANDREIA', 
      'F', 
      'ANDREIA@UOL.COM.BR', 
      'CEL', 
      '873453254',
      'CENTRO',
      'VITORIA',
      'ES'
);

CREATE TABLE JOGADORES (
      IDJOGADOR INT,
      NOME VARCHAR(30),
      ESTADO CHAR(2)
);

INSERT INTO JOGADORES VALUES (1, 'GUERRERO', 'RS')
INSERT INTO JOGADORES VALUES (2, 'GABIGOL', 'RJ')
INSERT INTO JOGADORES VALUES (3, 'GANSO', 'RJ')
INSERT INTO JOGADORES VALUES (4, 'NENE', 'RJ')
INSERT INTO JOGADORES VALUES (5, 'LOVE', 'SP')


CREATE VIEW V_JOGADORES AS 
SELECT NOME, ESTADO
FROM JOGADORES;

/*É APENAS PERMITIDO FAZER UPDATE NAS VIEWS COM JOIN*/
UPDATE V_RELATORIO SET NOME = 'JOSE' WHERE NOME = 'JORGE';


/*testando na view sem join */

DELETE FROM V_JOGADORES
WHERE NOME = 'GUERRERO';

INSERT INTO V_JOGADORES
VALUES ('GUERRERO', 'RS');

SELECT * FROM V_RELATORIO
WHERE SEXO = 'F';


/*ORDER BY */

CREATE TABLE ALUNOS (
      NUMERO INT,
      NOME VARCHAR(30)
);

INSERT INTO ALUNOS VALUES (1, 'JOAO');
INSERT INTO ALUNOS VALUES (1, 'MARIA');
INSERT INTO ALUNOS VALUES (2, 'ZOE');
INSERT INTO ALUNOS VALUES (2, 'ANDRE');
INSERT INTO ALUNOS VALUES (3, 'CLARA');
INSERT INTO ALUNOS VALUES (1, 'CLARA');
INSERT INTO ALUNOS VALUES (4, 'MAFRA');
INSERT INTO ALUNOS VALUES (5, 'JANAINA');
INSERT INTO ALUNOS VALUES (1, 'JANAINA');
INSERT INTO ALUNOS VALUES (3, 'MARCELO');
INSERT INTO ALUNOS VALUES (4, 'GIOVANNI');
INSERT INTO ALUNOS VALUES (5, 'ANTONIO');
INSERT INTO ALUNOS VALUES (6, 'ANA');
INSERT INTO ALUNOS VALUES (6, 'VIVIANE');

SELECT * FROM ALUNOS
ORDER BY NUMERO;

/*ORDENANDO POR COLUNA */
SELECT * FROM ALUNOS
ORDER BY 1;

/*ORDENANDO POR MAIS DE UMA COLUNA*/

SELECT * FROM ALUNOS
ORDER BY NUMERO, NOME;

/*MESCLANDO ORDER BY COM PROJECAO */

SELECT NOME FROM ALUNOS
ORDER BY NUMERO, NOME;


/* MAIOR P MENOR - MENOR P MAIOR */
SELECT * FROM ALUNOS
ORDER BY 1 DESC; 

SELECT * FROM ALUNOS
ORDER BY 1 ASC; 

SELECT * FROM ALUNOS
ORDER BY 1 DESC, 2 DESC; 


/* ORDENANDO COM JOIN */

SELECT C.NOME, 
       C.SEXO, 
       IFNULL(C.EMAIL, 'CLIENTE SEM EMAIL') AS "E-MAIL",
       T.TIPO, 
       T.NUMERO, 
       E.BAIRRO, 
       E.CIDADE, 
       E.ESTADO
FROM CLIENTE AS C
INNER JOIN ENDERECO AS E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE AS T
ON C.IDCLIENTE = T.ID_CLIENTE
ORDER BY 1;