/* SELECAO - PROJECAO - JUNCAO */

/*PROJECAO -> Tudo que voce quer ver na tela */

/*SELECAO -> Filtro da projecao (where), é um subconjunto do conjunto total de 
registro de uma tabela, a clause de selecao é o WHERE */

SELECT NOME, SEXO, EMAIL /*PROJECAO*/
FROM CLIENTE /*ORIGEM*/
WHERE SEXO = 'F' /*SELECAO*/


/* JUNCAO (JOIN) 2 TABELAS */

/*NOME, SEXO, BAIRRO, CIDADE */

SELECT NOME, SEXO, BAIRRO, CIDADE
FROM CLIENTE, ENDERECO
WHERE IDCLIENTE = ID_CLIENTE; 
 
SELECT NOME, SEXO, BAIRRO, CIDADE /*PROJECAO*/
FROM CLIENTE /*ORIGEM*/
  INNER JOIN ENDERECO /*JUNCAO*/
  ON IDCLIENTE = ID_CLIENTE
WHERE SEXO = 'F'; /*SELECAO*/
		
  
/*NOME, SEXO, EMAIL, TIPO, NUMERO */
SELECT NOME, SEXO, EMAIL, TIPO, NUMERO
FROM CLIENTE
INNER JOIN TELEFONE
ON IDCLIENTE = ID_CLINTE;


/*JOIN 3 TABELAS*/

/*NOME, SEXO, BAIRRO, CIDADE, TIPO, NUMERO*/

/*1 Forma: Ponteirando as tabelas */
SELECT CLIENTE.NOME, CLIENTE.SEXO, ENDERECO.BAIRRO, ENDERECO.CIDADE, TELEFONE.TIPO,TELEFONE.NUMERO
FROM CLIENTE
INNER JOIN ENDERECO 
ON CLIENTE.IDCLIENTE = ENDERECO.ID_CLIENTE
INNER JOIN TELEFONE
ON CLIENTE.IDCLIENTE = TELEFONE.ID_CLIENTE;


/*2 Forma: Dando Alias para as tabelas (AJUDA NA PERFORMANCE)*/
SELECT C.NOME, C.SEXO, E.BAIRRO, E.CIDADE, T.TIPO, T.NUMERO
FROM CLIENTE AS C
INNER JOIN ENDERECO AS E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE AS T
ON C.IDCLIENTE = T.ID_CLIENTE;




