/* Primeira forma normal */

/*1. Todo campo VETORIZADO se tornara outra tabela */

/*2. Todo campo MULTIVALORADO se tornara outra tabela */

CREATE DATABASE COMERCIO;
USE COMERCIO;


CREATE TABLE CLIENTE (
  IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
  NOME VARCHAR(30) NOT NULL,
  SEXO ENUM('M', 'F') NOT NULL,
  EMAIL VARCHAR(50) /*EMAIL UNICO, MAS PODE DEIXAR EM BRANCO */
  CPF VARCHAR (15) UNIQUE
);
