/* SELECAO - PROJECAO - JUNCAO */

/*PROJECAO -> Tudo que voce quer ver na tela */

/*SELECAO -> Filtro da projecao (where), é um subconjunto do conjunto total de 
registro de uma tabela, a clause de selecao é o WHERE */

SELECT NOME, SEXO, EMAIL /*PROJECAO*/
FROM CLIENTE /*ORIGEM*/
WHERE SEXO = 'F' /*SELECAO*/


/* JUNCAO (JOIN) 2 TABELAS */

/*NOME, SEXO, BAIRRO, CIDADE */

SELECT NOME, SEXO, BAIRRO, CIDADE
FROM CLIENTE, ENDERECO
WHERE IDCLIENTE = ID_CLIENTE; 
 
SELECT NOME, SEXO, BAIRRO, CIDADE /*PROJECAO*/
FROM CLIENTE /*ORIGEM*/
  INNER JOIN ENDERECO /*JUNCAO*/
  ON IDCLIENTE = ID_CLIENTE
WHERE SEXO = 'F'; /*SELECAO*/
		
  
/*NOME, SEXO, EMAIL, TIPO, NUMERO */
SELECT NOME, SEXO, EMAIL, TIPO, NUMERO
FROM CLIENTE
INNER JOIN TELEFONE
ON IDCLIENTE = ID_CLINTE;


/*JOIN 3 TABELAS*/

/*NOME, SEXO, BAIRRO, CIDADE, TIPO, NUMERO*/

/*1 Forma: Ponteirando as tabelas */
SELECT CLIENTE.NOME, CLIENTE.SEXO, ENDERECO.BAIRRO, ENDERECO.CIDADE, TELEFONE.TIPO,TELEFONE.NUMERO
FROM CLIENTE
INNER JOIN ENDERECO 
ON CLIENTE.IDCLIENTE = ENDERECO.ID_CLIENTE
INNER JOIN TELEFONE
ON CLIENTE.IDCLIENTE = TELEFONE.ID_CLIENTE;


/*2 Forma: Dando Alias para as tabelas (AJUDA NA PERFORMANCE)*/
SELECT C.NOME, C.SEXO, E.BAIRRO, E.CIDADE, T.TIPO, T.NUMERO
FROM CLIENTE AS C
INNER JOIN ENDERECO AS E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE AS T
ON C.IDCLIENTE = T.ID_CLIENTE;



/*
DML -> DATA MANIPULATION LANGUAGE
DDL -> DATA DEFINITION LANGUAGE
DCL -> DATA CONTROL LANGUAGE
TCL -> TRANSACTION CONTROL LANGUAGE
*/


/* INSERT */

INSERT INTO CLIENTE VALUES(NULL, 'PAULA', 'M', NULL, '45322342');
INSERT INTO ENDERECO VALUES(NULL,'RUA JOAQUIM SILVA','ALVORADA','NITEROI','RJ', 7);


/* FILTROS */
SELECT * FROM CLIENTE
WHERE SEXO = 'M';


/* UPDATE */

SELECT * FROM CLIENTE
WHERE IDCLIENTE = '7';

UPDATE CLIENTE
SET SEXO = 'F'
WHERE IDCLIENTE = '7';


/*DELETE*/
INSERT INTO CLIENTE VALUES(NULL, 'XXX', 'M', NULL, 'XXX');

SELECT * FROM CLIENTE;

SELECT * FROM CLIENTE
WHERE IDCLIENTE = 8;

DELETE FROM CLIENTE 
WHERE IDCLIENTE = 8;

/*COMANDOS DDL -> DATA DEFINITION LANGUAGE */

CREATE TABLE PRODUTO(
  IDPRODUTO INT PRIMARY KEY AUTO_INCREMENT,
  NOME_PRODUTO VARCHAR(30) NOT NULL,
  PRECO INT,
  FRETE FLOAT(10,2) NOT NULL
);

/* ALTER TABLE*/
/*ALTERANDO O NOME DE UMA COLUNA E TIPO - CHANGE */

ALTER TABLE PRODUTO 
CHANGE PRECO VALOR_UNITARIO INT NOT NULL;

ALTER TABLE PRODUTO
CHANGE VALOR_UNITARIO VALOR_UNITARIO INT;

/*MODIFY - ALTERA O TIPO*/

ALTER TABLE PRODUTO
MODIFY VALOR_UNITARIO VARCHAR(50) NOT NULL;

/*Change -> Mudar nome de coluna */
/*Modify -> Mudar tipo da coluna (ex int pra char) */

/*Adicionando Colunas */

ALTER TABLE PRODUTO 
ADD PESO FLOAT(10,2) NOT NULL;


/*APAGANDO UMA COLUNA*/

ALTER TABLE PRODUTO 
DROP COLUMN PESO;

/*ADICIONANDO UMA COLUNA NA ORDEM ESPECIFICA*/

ALTER TABLE PRODUTO 
ADD COLUMN PESO FLOAT(10,2) NOT NULL
AFTER NOME_PRODUTO;

ALTER TABLE PRODUTO 
ADD COLUMN PESO FLOAT(10,2) NOT NULL
FIRST; 