USE COMERCIO;

SELECT 
      C.NOME, 
      IFNULL(C.EMAIL, 'NAO POSSUI EMAIL'), 
      E.ESTADO, 
      T.NUMERO
FROM CLIENTE AS C
INNER JOIN ENDERECO AS E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE AS T
ON C.IDCLIENTE = T.ID_CLIENTE;


SELECT 
      C.NOME, 
      IFNULL(C.EMAIL, 'NAO POSSUI EMAIL') AS EMAIL, 
      E.ESTADO, 
      T.NUMERO
FROM CLIENTE AS C
INNER JOIN ENDERECO AS E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE AS T
ON C.IDCLIENTE = T.ID_CLIENTE;


