USE PROJETO;

CREATE TABLE VENDEDORES(
  IDVENDEDOR INT PRIMARY KEY AUTO_INCREMENT,
  NOME VARCHAR(30),
  SEXO CHAR(1),
  JANEIRO FLOAT(10, 2),
  FEVEREIRO FLOAT(10, 2),
  MARCO FLOAT(10, 2),
);



INSERT INTO VENDEDORES VALUES(NULL, 'CARLOS', 'M', 747743.22, 8845839.12, 9928.22);
INSERT INTO VENDEDORES VALUES(NULL, 'MARIA', 'F', 347743.22, 2845839.12, 19928.22);
INSERT INTO VENDEDORES VALUES(NULL, 'ANTONIO', 'M', 447743.22, 3845839.12, 29928.22);
INSERT INTO VENDEDORES VALUES(NULL, 'CLARA', 'F', 547743.22, 1845839.12, 39928.22);
INSERT INTO VENDEDORES VALUES(NULL, 'ANDERSON', 'M', 647743.22, 2845839.12, 79928.22);
INSERT INTO VENDEDORES VALUES(NULL, 'IVONE', 'F', 747743.22, 3845839.12, 29928.22);
INSERT INTO VENDEDORES VALUES(NULL, 'JOAO', 'M', 847743.22, 4845839.12, 49928.22);
INSERT INTO VENDEDORES VALUES(NULL, 'CELIA', 'F', 947743.22, 5845839.12, 69928.22);

/*MAX -> VALOR MAXIMO DE UMA COLUNA */

SELECT MAX(FEVEREIRO) AS MAIOR_FEV
FROM VENDEDORES;

/*MIN -> MENOR VALOR DE UMA COLUNA */
SELECT MIN(FEVEREIRO) AS MAIOR_FEV
FROM VENDEDORES;

/*AVG -> VALOR MEDIO DE UMA COLUNA */
SELECT AVG(FEVEREIRO) AS MAIOR_FEV
FROM VENDEDORES;

/*VARIAS FUNCOES*/
SELECT MAX(JANEIRO) AS MAX_JAN,
       MIN(JANEIRO) AS MIN_JAN,
       AVG(JANEIRO) AS MEDIA_JAN
FROM VENDEDORES; 

/*TRUNCATE -> FORMATA OS VALORES DECIMAIS TRUNCATE(1NUMERO, QTD) */
SELECT MAX(JANEIRO) AS MAX_JAN,
       MIN(JANEIRO) AS MIN_JAN,
       TRUNCATE(AVG(JANEIRO),2) AS MEDIA_JAN
FROM VENDEDORES; 

/*AGREGANDO COM O SUM()*/
SELECT SUM(JANEIRO) AS TOTAL_JANEIRO
FROM VENDEDORES;


SELECT SUM(JANEIRO) AS TOTAL_JANEIRO,
       SUM(FEVEREIRO) AS TOTAL_FEV,
       SUM(MARCO) AS TOTAL_MAR
FROM VENDEDORES;

/*VENDAS POR SEXO */

SELECT SEXO, SUM(MARCO) AS TOTAL_MARCO
FROM VENDEDORES
GROUP BY SEXO;

/*SUB QUERYS -> Quando o resultado de uma query de fora 
depende do resutlado de uma query de dentro.*/

/*VENDEDOR QUE VENDEU MENOS EM MARCO */
SELECT NOME, MIN(MARCO) AS MIN_MARCO
FROM VENDEDORES;

SELECT NOME, MIN(MARCO) AS MIN_MARCO
FROM VENDEDORES;

SELECT MIN(MARCO) FROM VENDEDORES;

SELECT NOME, MARCO FROM VENDEDOR
WHERE MARCO = (SELECT MIN(MARCO) FROM VENDEDORES);

SELECT NOME, FEVEREIRO FROM VENDEDORES
WHERE MARCO = (SELECT MAX(FEVEREIRO) FROM VENDEDORES);

SELECT NOME, MARCO FROM VENDEDORES
WHERE MARCO > (SELECT AVG(MARCO) FROM VENDEDORES);

/*SOMANDO AS LINHAS */

SELECT NOME, 
       JANEIRO,
       FEVEREIRO,
       MARCO,
       (JANEIRO+FEVEREIRO+MARCO) AS "TOTAL",
       TRUNCATE((JANEIRO+FEVEREIRO+MARCO)/3,2) AS "MEDIA",
       FROM VENDEDORES;

